/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:e11b5f1b80489a046df0e7c8dd3cc140:1176ffa0235cbeb7ffca2fbed152cad8:ffe0068b6a57b869c9458606dbc7be16$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class invader
	{
		public const string Invader2 = "invader2";
		public const string Invader3 = "invader3";
		public const string Invader4 = "invader4";
		public const string Invader5 = "invader5";
		public const string Invader6 = "invader6";
		public const string Invader7 = "invader7";
		public const string Invader8 = "invader8";
		public const string Invader9 = "invader9";
		public const string Invader10 = "invader10";
	}
}