/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:d250db37624428f4fc6c738e013967af:1176ffa0235cbeb7ffca2fbed152cad8:ca9644a97233e7a9e55aa9334e43ff47$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class invadersheet
	{
		public const string Invader2 = "invader2";
		public const string Invader3 = "invader3";
		public const string Invader4 = "invader4";
		public const string Invader5 = "invader5";
		public const string Invader6 = "invader6";
		public const string Invader7 = "invader7";
		public const string Invader8 = "invader8";
		public const string Invader9 = "invader9";
		public const string Invader10 = "invader10";
	}
}